services:
  db:
    image: postgres:13
    container_name: graph_api_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graph_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "graph_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  web:
    build: .
    container_name: fastapi
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
